"""Added 'name' to Board model

Revision ID: 30d9fa2b2bba
Revises: e4cb57f7a154
Create Date: 2023-10-11 21:30:49.564245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d9fa2b2bba'
down_revision: Union[str, None] = 'e4cb57f7a154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('name', sa.String(length=63), nullable=True))
    op.create_unique_constraint(None, 'boards', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boards', type_='unique')
    op.drop_column('boards', 'name')
    # ### end Alembic commands ###
